DESC DIM_PRODUTO;

SELECT
    CATEGORY_DESCRIPTION "Category",
    LISTAGG(PRODUCT_DESCRIPTION,';')
        WITHIN GROUP(ORDER BY PRODUCT_ID_INPUT_LEVEL) "Produtos"
FROM
    DIM_PRODUTO
GROUP BY
    CATEGORY_DESCRIPTION;
    