-- Consulta base:
SELECT DISTINCT CLASS_DESCRIPTION FROM DIM_PRODUTO;

-- UPPER, LOWER E INIT_CAP:

SELECT DISTINCT UPPER(CLASS_DESCRIPTION) FROM DIM_PRODUTO;

SELECT DISTINCT LOWER(CLASS_DESCRIPTION) FROM DIM_PRODUTO;

SELECT DISTINCT INITCAP(CLASS_DESCRIPTION) FROM DIM_PRODUTO;

--CONCAT
SELECT DISTINCT CONCAT(CONCAT(CLASS_ID, ' - '), CLASS_DESCRIPTION) AS "Identificador e classe" FROM DIM_PRODUTO;

--SUBSTR
SELECT DISTINCT SUBSTR(CLASS_DESCRIPTION, 1, 5) FROM DIM_PRODUTO;

--LENGTH
SELECT DISTINCT CLASS_DESCRIPTION, LENGTH(CLASS_DESCRIPTION) FROM DIM_PRODUTO;

--INSTR
SELECT DISTINCT CLASS_DESCRIPTION, INSTR(CLASS_DESCRIPTION, 'e') AS "Posição do 'e'" FROM DIM_PRODUTO;

--LPAD / RPAD
SELECT DISTINCT LPAD(CLASS_DESCRIPTION, 26, '*') FROM DIM_PRODUTO;

--REPLACE
SELECT DISTINCT REPLACE(CLASS_DESCRIPTION, 'e', '3') FROM DIM_PRODUTO;

--FILTRANDO RESULTADOS COM BASE EM MODIFICAÇÕES DE CADEIRAS DE CARACTERES:
SELECT DISTINCT CLASS_DESCRIPTION FROM DIM_PRODUTO WHERE SUBSTR(CLASS_DESCRIPTION, 1, 1) = 'P';